package com.roylenferink.bitbucket;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class Utils {

    private static final String[] BINARY_EXTENSIONS_VAL = new String[] {
            "7z",
            "a",
            "bin",
            "bmp",
            "bz2",
            "bzip2",
            "class",
            "dat",
            "deb",
            "dll",
            "doc",
            "docm",
            "docx",
            "dot",
            "dotm",
            "egg",
            "eol",
            "eot",
            "epub",
            "exe",
            "fla",
            "flac",
            "fli",
            "flv",
            "fpx",
            "fst",
            "fvt",
            "gif",
            "gz",
            "gzip",
            "ico",
            "img",
            "iso",
            "jar",
            "jpeg",
            "jpg",
            "jpgv",
            "jpm",
            "mkv",
            "mov",
            "mpeg",
            "mpg",
            "mpga",
            "o",
            "ogg",
            "ogv",
            "otf",
            "pdf",
            "pic",
            "png",
            "pot",
            "potm",
            "potx",
            "ppa",
            "ppam",
            "ppm",
            "pps",
            "ppsm",
            "ppsx",
            "ppt",
            "pptm",
            "pptx",
            "psd",
            "pya",
            "pyc",
            "pyo",
            "pyv",
            "qt",
            "rar",
            "raw",
            "rtf",
            "so",
            "swf",
            "tar",
            "tbz",
            "tbz2",
            "tga",
            "tgz",
            "tif",
            "tiff",
            "ttf",
            "xls",
            "xlsb",
            "xlsm",
            "xlsx",
            "xlt",
            "xltm",
            "xltx",
            "z",
            "zip",
            "zipx"
    };
    private static final Set<String> BINARY_EXTENSIONS = new HashSet<>(Arrays.asList(BINARY_EXTENSIONS_VAL));

    public static boolean isBinary(String extension) {
        return BINARY_EXTENSIONS.contains(extension);
    }

}
